### ISSUE TITLE
Is there a way to generate docsets for any dokx documentation?

### ISSUE THREAD

**Issue by vzhong** [ppwwyyxx/dash-docset-torch#1]
I just stumbled upon your docset and really appreciate it!

Would you happen to know if there's an universal procedure that can translate [dockx](https://github.com/deepmind/torch-dokx) generated documentation to Dash docsets? I'd like to reproduce what you've done with the torch repo to a number of other projects.

**Comment by ppwwyyxx** [comment]
Thanks for your interest! 
I don't know any existing tools doing that. But the `dashing` tool I used for torch is a convenient tool to translate any html documents to dash docset. So it should work for dockx as well.
I also included some common libraries in the docset, like nn, image, optim.
